### PR TITLE
Implement flow-store-service with Go

### PR DESCRIPTION
**Pull request by lixingwang**
1. Using redis Go library gopkg.in/redis.v4
2. Using godep vendor manage dependences

### CODE REVIEW

**Comment by fm-tibco** [comment]
Should we be checking in the vendor directory with third party source?

**Comment by lixingwang** [comment]
@fm-tibco This project now managed by godeps which put all dependences into vendor folder so that we can maintain stable dependence libs and vendor support after go 1.6 naturally.

That case any user or builder can build this project directly.
If we remove the vendor folder that mean very time we need checkout(Go get the dependence then build and run project). since go get latest master code which might affect stability. Please give your thought? thanks.

**Comment by fm-tibco** [comment]
It is ok for them to pull the dependencies in order to build, so I would go ahead and remove the vendor directory.

**Comment by lixingwang** [comment]
Replace with pull request #5

**Pull request closed without merging**
